server:
  port: 8001

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
website:
  domain-name: admin.sn.com
